spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jwt_security
    username: root
    password: mysqlserver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
